### ISSUE TITLE
Is it possible to reject a list number?

### ISSUE THREAD

**Issue by mjohn123** [geek4unix/unknown-caller-reject#7]
Hello, it is a good app,  although I was not success to run it.  I tried to call to my phone which installed your app. However, it does not reject the incoming call. To make sure it work, could you make an option which allows inserting rejected number. Then, the app. will reject the incoming call from the number. 

You are  successful for making the application to run in the background (as service), I tried to reset my phone and it is automatically turned on. Good job

**Comment by geek4unix** [comment]
Hi there Mjohn ! My apologies for such a delay in replying. I will get a notification setup or something for any more replies :)

With regard to which number it blocks , it would be a trivial change to have a list of blocked numbers.. It was designed to block calls which have no caller ID , and no telephone number shown, which in the UK / Europe is where most advertising and spam calls come from.

I did use something similar when testing my code, so i could make a change that had a list of numbers you would like to block if you would find it helps.

Many thanks on the comment about running as a service, I can see you are a man of taste and finesse ! I also agree running as a service is nice.

Finally, id like to ask your opinion about the notification bar ... I have considered removing it until a call is blocked, i get bored of seeing it when its doing nothing. Im interested in your opinion on that.

Thanks for your message

Neil

**Comment by geek4unix** [comment]
[app-debug.apk.zip](https://github.com/geek4unix/unknown-caller-reject/files/628950/app-debug.apk.zip)

Mjohn123: I have a new version for you , as it is off a debug nature, i did not want to release it fully yet. I've installed and tested it with the debugger running and a caller from skype without a caller ID set. 

Would be great to hear how people get on testing it.

**Comment by mjohn123** [comment]
Thank you so much
